version: '2'
services:

### Nginx ###
    webserver:
      image: nginx:1.14.0-alpine
      container_name: nginx_1.14
      links:
        - app
      ports:
        - "80:80"
      volumes:
        - ./web/default.conf:/etc/nginx/conf.d/default.conf

### PHP ###
    app:
      build: ./php
      container_name: php_fpm
      links:
        - dbserver
      volumes:
        - ./src:/var/www:cached

### MySQL###
    dbserver:
      image: mysql:5.7
      container_name: mysql_5.7
      ports: 
        - "3036:3036"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=laravel-db
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=laravel
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      volumes_from:
        - data

### 保存領域 ###
    data:
      image: busybox
      container_name: data-container
